<a href="https://colab.research.google.com/github/MDYeaminIslam/Codeforces-Solutions-Python/blob/Master/AI_lab_week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# ***NumPy Installation***
Google Colab and Anaconda Package include Python, NumPy, and other commonly used packages for scientific computing and data science.

NumPy can be installed with conda, with pip, or with a package manager on different OS.

If you use conda, you can install it with: conda install numpy

If you use pip, you can install it with: pip install numpy

But here we don't need any installation process.

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])
numbers

array([ 2,  3,  5,  7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
array_1D = np.array([2,4,5,6])
array_1D

array([2, 4, 5, 6])

In [5]:
array_2D = np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]]) ## 3X4 array--(3 rows and 4 columns)
array_2D 

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [6]:
array_3D = np.array([[[2,4,5,6],[2,4,5,6],[2,4,5,6]]])
array_3D 

array([[[2, 4, 5, 6],
        [2, 4, 5, 6],
        [2, 4, 5, 6]]])

In [ ]:
import numpy as np
output = np.array([[x for x in range(2,21,2)],[x for x in range(1,22,2)]])
output

array([list([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]),
       list([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])], dtype=object)

In [7]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats    #NumPy does not display trailing 0s to the right of the decimal point in floating-point values.

array([0. , 0.1, 0.2, 0.3, 0.4])

In [9]:
strings = np.array(['apple','big','cat'])
strings 

array(['apple', 'big', 'cat'], dtype='<U5')

# ***Checking an array's element types***

In [10]:
integers.dtype

dtype('int64')

In [11]:
floats.dtype

dtype('float64')

In [12]:
strings.dtype

dtype('<U5')

# ***Checking an array’s Dimensions and Shape***

In [13]:
array_1D.ndim

1

In [14]:
array_2D.ndim

2

In [15]:
array_3D.ndim

3

In [16]:
array_3D.shape

(1, 3, 4)

In [17]:
array_2D.shape

(3, 4)

In [18]:
integers.size

6

In [19]:
integers.itemsize

8

In [20]:
floats.size

5

In [21]:
floats.itemsize

8