<a href="https://colab.research.google.com/github/MDYeaminIslam/Codeforces-Solutions-Python/blob/Master/AI_week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Universal Functions***

In [3]:
import numpy as np

In [ ]:
num = np.array([1, 4, 9, 16, 25, 36])

In [ ]:
np.sqrt(num)

array([1., 2., 3., 4., 5., 6.])

In [ ]:
num2 = np.arange(0, 6) * 10
num2 

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
num3 = np.array([1, 2, 4, 5, 10, 15])
np.add(num, num2)

array([ 1, 14, 29, 46, 65, 86])

In [ ]:
np.mod(num,num3)

array([0, 0, 1, 1, 5, 6])

In [ ]:
np.remainder(num,num3)

array([0, 0, 1, 1, 5, 6])

# ***Array Product***

In [ ]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [ ]:
A * B    # elementwise product


array([[2, 0],
       [0, 4]])

In [ ]:
np.multiply(A,B)

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B    # matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)

array([[5, 4],
       [3, 4]])

# ***Exponents and Logarithms***

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.power(3, 3)

27

In [ ]:
np.log10(2)

0.3010299956639812

In [ ]:
np.log2(4)

2.0

In [ ]:
a = 5
np.power(a,2)

25

# ***Trigonometric Functions***

In [ ]:
import math
value = np.array([0,30,45,60,90])

In [ ]:
a = np.sin(value*math.pi/180)  #the result is in Radians
a

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
result = np.arcsin(a)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.degrees(result)

array([ 0., 30., 45., 60., 90.])

In [ ]:
np.cos(value)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [ ]:
res = np.tan(value*np.pi/180) # result in Degree
res

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [ ]:
inverseOfTan = np.arctan(res)
inverseOfTan

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.degrees(inverseOfTan)

array([ 0., 30., 45., 60., 90.])

TypeError: ignored

TypeError: ignored

# ***Indexing***

In [ ]:
num = np.array([1, 4, 9, 16, 25, 36])
num[1:]

array([ 4,  9, 16, 25, 36])

In [ ]:
grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90], 
                   [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [ ]:
grades[2] #select a single row, specify only one index in square brackets

array([94, 77, 90])

In [ ]:
grades[0:2] #select multiple sequential rows, use slice notation

array([[ 87,  96,  70],
       [100,  87,  90]])

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

NameError: ignored

In [6]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[4:6, 1:3]

array([[ 6,  7],
       [10, 11]])

In [8]:
a[2:5, 2:4]  #Selecting a Subset of a Two-Dimensional array’s Columns

array([[11, 12],
       [ 3,  4],
       [ 7,  8]])

In [ ]:
a[3:4, 2:4]

# ***Shallow and Deep Copy***

In [9]:
import copy

li1 = [1, 2, [3,5], 4] 

In [11]:
li2 = copy.deepcopy(li1) 
li2

[1, 2, [3, 5], 4]

In [13]:
li2[2][0] = 'Z'
li2

[1, 2, ['Z', 5], 4]

In [15]:
temp = np.linspace(0,100,12)
temp

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [16]:
temp.shape

(12,)

In [17]:
temperatures = np.around(temp, decimals=1)
temperatures

array([  0. ,   9.1,  18.2,  27.3,  36.4,  45.5,  54.5,  63.6,  72.7,
        81.8,  90.9, 100. ])

In [18]:
t1 = temperatures.reshape(3,4)
t1

array([[  0. ,   9.1,  18.2,  27.3],
       [ 36.4,  45.5,  54.5,  63.6],
       [ 72.7,  81.8,  90.9, 100. ]])

In [19]:
t2 = temperatures.reshape(2,3,2)
t2

array([[[  0. ,   9.1],
        [ 18.2,  27.3],
        [ 36.4,  45.5]],

       [[ 54.5,  63.6],
        [ 72.7,  81.8],
        [ 90.9, 100. ]]])

In [20]:
z = np.swapaxes(t2, 0, 2)
z

array([[[  0. ,  54.5],
        [ 18.2,  72.7],
        [ 36.4,  90.9]],

       [[  9.1,  63.6],
        [ 27.3,  81.8],
        [ 45.5, 100. ]]])

In [21]:
z.T

array([[[  0. ,   9.1],
        [ 18.2,  27.3],
        [ 36.4,  45.5]],

       [[ 54.5,  63.6],
        [ 72.7,  81.8],
        [ 90.9, 100. ]]])